site_name: Seismo Tools

nav:
    - Tutorials: tutorials/tutorials.md
    - How-to Guides: howto/howto.md
    - Reference: reference/reference.md
    - Discussions: discussions/discussions.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: readthedocs
