#!/bin/bash
#: Title       : getjul - output day of year from year-month-day date
#: Synopsis    : getjul 2000-12-31 or getjul 2000 12 31
#: Date        : 2018-08-28
#: Author      : "Antonio Villasenor" <antonio.villasenor@csic.es>
#: Version     : 1.0
#: Requirements: POSIX date command (gdate in macOS)
#: Arguments   : date
#: Options     : none
set -u # error if variable undefined
set -o pipefail

if command -v date > /dev/null && date --version > /dev/null 2>&1; then
    DATE=date
elif command -v gdate > /dev/null && gdate --version > /dev/null 2>&1; then
    DATE=gdate
else
    echo "ERROR: no GNU date command in this system"
    exit 1
fi

progname=${0##*/}

if [[ $# -eq 1 ]]; then
	$DATE -u --date="${1}" +%j
elif [[ $# -eq 3 ]]; then
	year=$1
	month=$2
	day=$3
	$DATE -u --date="${year}-${month}-${day}" +%j
else
	echo "usage: $progname year month day | year-month-day"
	exit 1
fi
